# YAML Linting Configuration
---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  brackets:
    max-spaces-inside: 0
  braces:
    max-spaces-inside: 1

ignore: |
  .venv/
  site/
  tmp/
  artifacts/
