site_name: RepoQ - Semantic Meta-Quality Loop
site_description: Revolutionary repository quality analysis with ontological intelligence
site_author: RepoQ Contributors
site_url: https://kirill-0440.github.io/repoq

repo_name: kirill-0440/repoq
repo_url: https://github.com/kirill-0440/repoq
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 RepoQ Contributors

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kirill-0440/repoq
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/repoq/
  
  version:
    provider: mike
    default: stable

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: kirill-0440
      repo: repoq
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - autorefs
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ?
          'dark' : 'light'
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]  # Add current directory to Python path
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_submodules: false
            show_source: true
            show_bases: true
            show_inheritance_diagram: false  # Disable to avoid graphviz dependency issues
            members_order: source
            group_by_category: true
            show_category_heading: true
            show_signature_annotations: true
            separate_signature: true
            show_if_no_docstring: false  # Hide members without docstrings

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - User Guide:
    - Overview: user-guide/usage.md
    - Configuration: user-guide/configuration.md
    - CLI Commands: user-guide/commands.md
    - Workflows: user-guide/workflows.md
  - Advanced Topics:
    - Meta-Quality Loop: ontology/meta-loop.md
    - Ontological Intelligence: ontology/intelligence.md
    - TRS Framework: ontology/trs-framework.md
  - Development:
      - Development Overview: development/index.md
      - uv Setup Guide: development/uv-setup.md
      - Contributing Guide: development/CONTRIBUTING.md
      - Testing Strategy: development/testing.md
      - Mathematical Proof (Quality Monotonicity): development/mathematical-proof-quality-monotonicity.md
      - Formal Foundations: development/formal-foundations-complete.md
      - Formal Diagrams: development/formal-diagrams.md
      - Quality Loop Roadmap: development/quality-loop-roadmap.md
      - tmp/ Artifacts Inventory: development/tmp-artifacts-inventory.md
  - VDAD Process:
      - Phase 1 - Domain Context: vdad/phase1-domain-context.md
      - Phase 1 - Stakeholders: vdad/phase1-stakeholders.md
      - Phase 2 - Value Register: vdad/phase2-value-register.md
      - Phase 3 - Requirements: vdad/phase3-requirements.md
      - Phase 4 - Architecture Overview: vdad/phase4-architecture-overview.md
      - Phase 4 - C4 Diagrams: vdad/phase4-c4-diagrams.md
      - Phase 4 - ADRs: vdad/phase4-adrs.md
      - Phase 4 - NFR Realization: vdad/phase4-nfr-realization.md
      - Phase 4 - BAML Agent: vdad/phase4-baml-agent.md
  - API Reference:
    - Overview: api/reference.md
  - About:
    - Current Limitations: about/limitations.md

watch:
  - repoq/