name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide details to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what went wrong
      placeholder: When I run `repoq full ./my-repo`, I expected X but got Y...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Clone repository: git clone https://github.com/example/repo
        2. Run command: repoq structure ./repo --format json
        3. See error: ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages and stack traces.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System information
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.11.5
        - RepoQ: 2.0.0
        - Repository size: ~1000 files, 50k LOC
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (crashes, data loss)
        - High (major feature broken)
        - Medium (minor feature issue)
        - Low (cosmetic, workaround exists)
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I searched existing issues for duplicates
          required: true
        - label: I can reproduce this bug consistently
          required: true
        - label: I included all relevant error messages
          required: true
        - label: I tested with the latest RepoQ version
          required: false